version: '3'

services:
        db:
                build: DockerPostgres/
                image: postgresflaviani
                restart: always
        web:
                build: DockerTomcat/
                image: tomcatflaviani
                ports:
                        - "80:8080"
                depends_on:
                        - db
                restart: always
