package com.howtodoinjava.entity;
// Generated 20/05/2014 05:39:04 AM by Hibernate Tools 3.2.1.GA

import com.howtodoinjava.lambdacalculo.Term;
import org.springframework.util.SerializationUtils;




/**
 * Termino generated by hbm2java
 */
public class Termino  implements java.io.Serializable {


     private TerminoId id;
     private Usuario usuario;
     private String combinador;
     private byte[] serializado;
     public Term termObject;

    public Termino() {
    }

    public Termino(TerminoId id, Usuario usuario, String combinador, byte[] serializado) {
       this.id = id;
       this.usuario = usuario;
       this.combinador = combinador;
       this.serializado = serializado;
    }
   
    public TerminoId getId() {
        return this.id;
    }
    
    public void setId(TerminoId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCombinador() {
        return this.combinador;
    }
    
    public void setCombinador(String combinador) {
        this.combinador = combinador;
    }
    public byte[] getSerializado() {
        return this.serializado;
    }
    
    public void setSerializado(byte[] serializado) {
        this.serializado = serializado;
    }
    
    public Term getTermObject()
    {
        return this.termObject;
    }
    
    public void setTermObject(Term t)
    {
         this.termObject=t;
         this.serializado= SerializationUtils.serialize(t);
    }
    
    public String toString()
    {
        return this.termObject.toString();
    }




}
