package com.howtodoinjava.entity;
// Generated 21/05/2014 08:27:39 PM by Hibernate Tools 3.2.1.GA

import javax.validation.constraints.Pattern;
import org.hibernate.validator.constraints.Length;

/**
 * TerminoId generated by hbm2java
 */
public class TerminoId  implements java.io.Serializable {

    @Length(min=1,message="No puede dejar el campo del Alias vac&iacute;o")
    @Pattern(regexp="^[A-Z][a-z]+$",message="El alias debe empezar en mayuscula y los demas caracteres en minuscula")
     private String alias;
     private String login;

    public TerminoId() {
    }

    public TerminoId(String alias, String login) {
       this.alias = alias;
       this.login = login;
    }
   
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TerminoId) ) return false;
		 TerminoId castOther = ( TerminoId ) other; 
         
		 return ( (this.getAlias()==castOther.getAlias()) || ( this.getAlias()!=null && castOther.getAlias()!=null && this.getAlias().equals(castOther.getAlias()) ) )
 && ( (this.getLogin()==castOther.getLogin()) || ( this.getLogin()!=null && castOther.getLogin()!=null && this.getLogin().equals(castOther.getLogin()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAlias() == null ? 0 : this.getAlias().hashCode() );
         result = 37 * result + ( getLogin() == null ? 0 : this.getLogin().hashCode() );
         return result;
   }   


}


